# Generated by Django 3.1.2 on 2021-06-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='link',
            field=models.CharField(default=' ', max_length=10000),
        ),
    ]
